### ISSUE TITLE
How did the RUT get the sentence?

### ISSUE THREAD

**Issue by nicklasb** [giacinti/nmea2mqtt#1]
Hi, just a question, how did you get the NMEA-sentence to the RUT? 
And what RUT was it?

**Comment by nicklasb** [comment]
Sorry, realized this was like likely the internal RUT GPS. Closing.

**Comment by giacinti** [comment]
@nicklasb indeed this one listens to NMEA sentences forwarded by the RUT (port 8500) and send them back to MQTT as json payload. I couldn't use a simple pull of the data from cron for example as I wanted a higher interval than 1 minute
